# support SPA setup
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "build/"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "14.5.0"
  # use .env.production to change env variables needed during build
